version: '3.8'

services:
  hfl-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hfl_server
    restart: always
    ports:
      - "5000:80"        # API & DoH (/dns-query)
      - "53:53/udp"      # Native UDP DNS
      - "53:53/tcp"      # Native TCP DNS
    environment:
      - BOT_TOKEN=8649333793:AAFTEfrJiqN0FQyLPuL3Sx0idg0earZHoA8
      - ADMIN_TELEGRAM_ID=6014501462
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./data:/app/data
